Repository fga-eps-mds/2019.1-Ludum, pull requests merged in 2019-05, with the labels that each got.

#112 US16 - Exibir informações sobre a funcionalidade de Contribuição
  rasa/data/intents/geral.md
  rasa/data/stories/geral.md
  rasa/domain.yml
  rasa/models/dialogue/domain.yml
Labels: MDS, User Story, enhancement

#121 Bug/01
  rasa/actions/actions.py
  rasa/actions/question.py
  rasa/models/dialogue/domain.json
  rasa/models/nlu/current/training_data.json
Labels: Bug, MDS

#128 US25 - Refatoração do menu Inicial
  rasa/credentials.yml
  rasa/domain.yml
  rasa/models/dialogue/domain.yml
Labels: MDS, User Story, enhancement

#127 US13 - Selecionar complexidade do jogo no tutorial
  rasa/credentials.yml
  rasa/domain.yml
  rasa/models/dialogue/domain.yml
Labels: MDS, User Story, enhancement

#133 TS09 - Criar jogo com maior complexidade
  docs/imagens/atualizandoMovimentos.png
  docs/imagens/classeSnake1.png
  docs/imagens/classeSnake2.png
  docs/imagens/classegame1.png
  docs/imagens/comida2.png
  docs/imagens/cores.png
  docs/imagens/desenhoEpontos.png
  docs/imagens/direcao.png
  docs/imagens/eventosEdirecao.png
  docs/imagens/imports.png
  docs/tutorialSnake.md
Labels: MDS, Technical Story

#145 US11 - Visualizar FAQ
  docs/perguntas_faq.md
  rasa/actions/actions.py
  rasa/actions/faq/perguntas_faq.txt
  rasa/actions/perguntas_faq.md
  rasa/data/intents/geral.md
  rasa/data/stories/geral.md
  rasa/data/stories/onlineTraining.md
  rasa/data/storiesinteractive.md
  rasa/domain.yml
  rasa/models/dialogue/domain.json
  rasa/models/dialogue/domain.yml
  rasa/models/nlu/current/training_data.json
Labels: User Story

#146 US14 - Aprender a criar um jogo de baixa complexidade
  rasa/data/intents/geral.md
  rasa/data/stories.md
  rasa/data/stories/geral.md
  rasa/domain.yml
  rasa/models/dialogue/domain.yml
Labels: User Story, enhancement
