Repository fga-eps-mds/2019.1-Ludum, pull requests merged in 2019-04, with the labels that each got.

#21 Docs/t07(Documento de Visão)
  docs/Documento_Visao.md
Labels: Document, MDS, Technical

#30 Configuração do Docker
  Dockerfile
  docker-compose.yml
Labels: Critical, EPS, Technical

#32 Docs/t23
  docs/documento-de-arquitetura.md
Labels: Document, MDS, Technical

#67 Feature/US02
  .gitignore
  Dockerfile
  requirements.txt
  runtime.txt
  src/helloLudum.py
  src/requirements.txt
  src/runtime.txt
Labels: Feature, MDS, User Story

#49 Feature/us01
  .vscode/settings.json
  src/helloLudum.py
Labels: Feature, MDS, User Story

#69 Atualizando master com commits da development
  .gitignore
  .vscode/settings.json
  Dockerfile
  docs/_sidebar.md
  docs/imagens/RoadMap_Produto-Release_1.png
  docs/imagens/RoadMap_Produto-Release_2.png
  docs/roadmap-produto.md
  requirements.txt
  src/helloLudum.py
Labels: EPS, MDS

#75 US05 - Exibir informações sobre a funcionalidade de resolução de dúvidas
  .gitignore
  .gitlab-ci.yml
  Dockerfile
  bot.requirements.txt
  docker-compose.yml
  docker/actions.Dockerfile
  docker/actions.requirements.txt
  rasa/Makefile
  rasa/actions/actions.py
  rasa/credentials.yml
  rasa/data/intents/actions.md
  rasa/data/intents/aleatorio.md
  rasa/data/intents/geral.md
  rasa/data/stories/actions.md
  rasa/data/stories/aleatorio.md
  rasa/data/stories/geral.md
  rasa/domain.yml
  rasa/endpoints.yml
  rasa/models/dialogue/domain.json
  rasa/models/dialogue/domain.yml
  rasa/models/dialogue/policy_0_KerasPolicy/featurizer.json
  rasa/models/dialogue/policy_0_KerasPolicy/keras_model.h5
  rasa/models/dialogue/policy_0_KerasPolicy/keras_policy.json
  rasa/models/dialogue/policy_1_FallbackPolicy/fallback_policy.json
  rasa/models/dialogue/policy_2_MemoizationPolicy/featurizer.json
  rasa/models/dialogue/policy_2_MemoizationPolicy/memorized_turns.json
  rasa/models/dialogue/policy_metadata.json
  rasa/models/nlu/current/checkpoint
  rasa/models/nlu/current/crf_model.pkl
  rasa/models/nlu/current/intent_classifier_tensorflow_embedding.ckpt.data-00000-of-00001
  rasa/models/nlu/current/intent_classifier_tensorflow_embedding.ckpt.index
  rasa/models/nlu/current/intent_classifier_tensorflow_embedding.ckpt.meta
  rasa/models/nlu/current/intent_classifier_tensorflow_embedding_encoded_all_intents.pkl
  rasa/models/nlu/current/intent_classifier_tensorflow_embedding_inv_intent_dict.pkl
  rasa/models/nlu/current/intent_featurizer_count_vectors.pkl
  rasa/models/nlu/current/metadata.json
  rasa/models/nlu/current/training_data.json
  rasa/nlu_config.yml
  rasa/policy_config.yml
  rasa/train.py
  rasa/validator.py
  src/helloLudum.py
Labels: MDS, User Story, enhancement

#78 US03 - Exibir informações sobre a funcionalidade de configuração do ambiente
  rasa/credentials.yml
  rasa/data/intents/geral.md
  rasa/data/stories/geral.md
  rasa/domain.yml
  rasa/models/dialogue/domain.json
  rasa/models/dialogue/domain.yml
  rasa/models/dialogue/policy_metadata.json
  rasa/validator.py
Labels: MDS, User Story, enhancement

#77 US06 - Exibir informações sobre a funcionalidade de auxílio no desenvolvimento de jogos
  rasa/data/intents/geral.md
  rasa/data/stories/geral.md
  rasa/domain.yml
  rasa/models/dialogue/domain.json
  rasa/models/dialogue/domain.yml
  rasa/models/dialogue/policy_0_KerasPolicy/featurizer.json
  rasa/models/dialogue/policy_0_KerasPolicy/keras_model.h5
  rasa/models/dialogue/policy_2_MemoizationPolicy/memorized_turns.json
  rasa/models/dialogue/policy_metadata.json
  rasa/models/nlu/current/crf_model.pkl
  rasa/models/nlu/current/intent_classifier_tensorflow_embedding.ckpt.data-00000-of-00001
  rasa/models/nlu/current/intent_classifier_tensorflow_embedding.ckpt.index
  rasa/models/nlu/current/intent_classifier_tensorflow_embedding.ckpt.meta
  rasa/models/nlu/current/intent_classifier_tensorflow_embedding_inv_intent_dict.pkl
  rasa/models/nlu/current/intent_featurizer_count_vectors.pkl
  rasa/models/nlu/current/metadata.json
  rasa/models/nlu/current/training_data.json
Labels: MDS, User Story, enhancement

#83 TS06 - Criar comunicação com o core do Ludum para o Microsserviço de Dúvidas
  Dockerfile
  docker/actions.Dockerfile
  rasa/actions/question.py
  rasa/data/intents/actions.md
  rasa/data/stories/actions.md
  rasa/domain.yml
Labels: EPS, Technical Story

#105 T36 - Refinar comunicação do Ludum
  rasa/data/intents/geral.md
  rasa/data/stories/geral.md
  rasa/domain.yml
  rasa/models/dialogue/domain.json
  rasa/models/dialogue/domain.yml
  rasa/models/dialogue/policy_0_KerasPolicy/featurizer.json
  rasa/models/dialogue/policy_0_KerasPolicy/keras_model.h5
  rasa/models/dialogue/policy_2_MemoizationPolicy/memorized_turns.json
  rasa/models/dialogue/policy_metadata.json
  rasa/models/nlu/current/crf_model.pkl
  rasa/models/nlu/current/intent_classifier_tensorflow_embedding.ckpt.data-00000-of-00001
  rasa/models/nlu/current/intent_classifier_tensorflow_embedding.ckpt.index
  rasa/models/nlu/current/intent_classifier_tensorflow_embedding.ckpt.meta
  rasa/models/nlu/current/intent_classifier_tensorflow_embedding_encoded_all_intents.pkl
  rasa/models/nlu/current/intent_classifier_tensorflow_embedding_inv_intent_dict.pkl
  rasa/models/nlu/current/intent_featurizer_count_vectors.pkl
  rasa/models/nlu/current/metadata.json
  rasa/models/nlu/current/training_data.json
Labels: MDS, Technical

#106 US07 - Consultar características do ambiente do usuário
  rasa/data/intents/geral.md
  rasa/data/nlu_interactive.md
  rasa/data/stories.md
  rasa/data/stories/geral.md
  rasa/data/stories/onlineTraining.md
  rasa/data/storiesinteractive.md
  rasa/domain.yml
  rasa/models/dialogue/domain.json
  rasa/models/dialogue/domain.yml
  rasa/models/dialogue/policy_0_KerasPolicy/featurizer.json
  rasa/models/dialogue/policy_0_KerasPolicy/keras_model.h5
  rasa/models/dialogue/policy_1_FallbackPolicy/fallback_policy.json
  rasa/models/dialogue/policy_2_MemoizationPolicy/memorized_turns.json
  rasa/models/dialogue/policy_metadata.json
  rasa/models/nlu/current/crf_model.pkl
  rasa/models/nlu/current/intent_classifier_tensorflow_embedding.ckpt.data-00000-of-00001
  rasa/models/nlu/current/intent_classifier_tensorflow_embedding.ckpt.index
  rasa/models/nlu/current/intent_classifier_tensorflow_embedding.ckpt.meta
  rasa/models/nlu/current/intent_classifier_tensorflow_embedding_encoded_all_intents.pkl
  rasa/models/nlu/current/intent_classifier_tensorflow_embedding_inv_intent_dict.pkl
  rasa/models/nlu/current/intent_featurizer_count_vectors.pkl
  rasa/models/nlu/current/metadata.json
  rasa/models/nlu/current/training_data.json
  rasa/novotrain.py
  rasa/policy_config.yml
  rasa/story_graph.dot
Labels: Feature, MDS, User Story
