Repository fga-eps-mds/2019.1-Ludum, pull requests merged in 2019-06, with the labels that each got.

#149 US15 - Aprender a criar um jogo de maior complexidade
  docs/imagens/1-.png
  docs/imagens/10-.png
  docs/imagens/11-.png
  docs/imagens/2-.png
  docs/imagens/3-.png
  docs/imagens/4-.png
  docs/imagens/5-.png
  docs/imagens/6-.png
  docs/imagens/7-.png
  docs/imagens/8-.png
  docs/imagens/9-.png
  rasa/credentials.yml
  rasa/data/intents/aleatorio.md
  rasa/data/intents/geral.md
  rasa/data/stories/geral.md
  rasa/domain.yml
  rasa/models/dialogue/domain.json
  rasa/models/dialogue/domain.yml
Labels: User Story, enhancement

#174 T64 - Refatorar fluxo de ambiente
  rasa/data/intents/geral.md
  rasa/data/stories/geral.md
  rasa/domain.yml
  rasa/models/dialogue/domain.json
  rasa/models/dialogue/domain.yml
  rasa/models/dialogue/policy_0_KerasPolicy/featurizer.json
  rasa/models/dialogue/policy_0_KerasPolicy/keras_model.h5
  rasa/models/dialogue/policy_0_KerasPolicy/keras_policy.json
  rasa/models/dialogue/policy_1_FallbackPolicy/fallback_policy.json
  rasa/models/dialogue/policy_2_MemoizationPolicy/featurizer.json
  rasa/models/dialogue/policy_2_MemoizationPolicy/memorized_turns.json
  rasa/models/dialogue/policy_3_FormPolicy/featurizer.json
  rasa/models/dialogue/policy_3_FormPolicy/memorized_turns.json
  rasa/models/dialogue/policy_metadata.json
  rasa/models/nlu/current/crf_model.pkl
  rasa/models/nlu/current/intent_classifier_sklearn.pkl
  rasa/models/nlu/current/metadata.json
  rasa/models/nlu/current/regex_featurizer.json
  rasa/models/nlu/current/training_data.json
Labels: Bug, enhancement

#170 US20 - Visualizar tutoriais da comunidade
  rasa/actions/actions.py
  rasa/actions/question.py
  rasa/data/intents/geral.md
  rasa/models/dialogue/domain.json
  rasa/models/dialogue/domain.yml
  rasa/models/dialogue/policy_0_KerasPolicy/featurizer.json
  rasa/models/dialogue/policy_0_KerasPolicy/keras_model.h5
  rasa/models/dialogue/policy_0_KerasPolicy/keras_policy.json
  rasa/models/dialogue/policy_1_FallbackPolicy/fallback_policy.json
  rasa/models/dialogue/policy_2_MemoizationPolicy/featurizer.json
  rasa/models/dialogue/policy_2_MemoizationPolicy/memorized_turns.json
  rasa/models/dialogue/policy_3_FormPolicy/featurizer.json
  rasa/models/dialogue/policy_3_FormPolicy/memorized_turns.json
  rasa/models/dialogue/policy_metadata.json
  rasa/models/nlu/current/crf_model.pkl
  rasa/models/nlu/current/intent_classifier_sklearn.pkl
  rasa/models/nlu/current/metadata.json
  rasa/models/nlu/current/regex_featurizer.json
  rasa/models/nlu/current/training_data.json
Labels: enhancement

#178 US22 - Acessar tutorial da comunidade
  rasa/actions/actions.py
  rasa/data/intents/geral.md
  rasa/data/stories/geral.md
  rasa/domain.yml
Labels: Feature, enhancement
